################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

################ Indonesia language ##################
[id]
languageName = "Id"
languageCode = "id-id"
contentDir = "content/indonesia"
weight = 2
